### ISSUE TITLE
organism flag?

### ISSUE THREAD

**Issue by r-mashoodh** [loosolab/TOBIAS_snakemake#18]
Hello I am trying to run a non-model organism through TOBIAS ...

```
run_info:
  organism: insect  
```

I have added the genome size to macs

```
macs: "--gsize 222255331 --nomodel --shift -100 --extsize 200 --broad"
```

but I get the following error:
```
ERROR: Could not find key(s) "run_info:organism" in configfile /. Please check that your configfile has right format for TOBIAS.
SystemExit in line 75 of /mnt/beegfs/home5/TOBIAS_snakemake/Snakefile.
  File "/mnt/beegfs/home5/TOBIAS_snakemake/Snakefile", line 75, in <module>
```

I can change the organism to 'mouse', and it runs but then I get an error bc I also don't have a `blacklist.bed`. Will putting in 'mouse' affect the run at all? Can I just use `data/blacklist.bed`?

I'm unable to comment the `blacklist` and `organism` lines out it seems.

any advice would be appreciated!

r.

**Comment by mohobein** [comment]
Hey @r-mashoodh,

you can just leave `organism: mouse` if you already adjusted the genome size for macs to match your true organism. You also need to go to `snakefiles/preprocessing.snake` and remove [line 118](https://github.com/loosolab/TOBIAS_snakemake/blob/0daca76db03b3978c340a32b854d2a4ad280417d/snakefiles/preprocessing.snake#L118) from it which would provide the mouse genome size to the macs call instead. 
However, you cannot use the blacklisted regions provided in the TOBIAS example data, as these regions only exist in the human genome. The regions in that file will be ignored for the analysis because they have too much noise. If there are no such regions for the analysis you want to do, you can try a workaround by just creating an empty file that you use as input for the pipeline (for example by just using the bash command `touch my_blacklist.bed` and putting the path to that file into the config file).

Let me know if this worked for you!

Best regards,
Moritz

**Comment by r-mashoodh** [comment]
thanks @mohobein !

here is my command ...

```
snakemake --configfile sex_config.yaml --use-conda --cluster "sbatch --cpus-per-task={threads}" --jobs 30  
```

It starts plotting but then at some point I get the following error ...

```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 2
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	plot_aggregate_within
	1

[Wed Oct 30 15:32:55 2024]
Job 0: Plotting split between bound/unbound around TFBS for TF "Mecom_MA0029.2" in condition "Female"

Activating conda environment: /mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4
Traceback (most recent call last):
  File "/mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4/bin/TOBIAS", line 8, in <module>
    sys.exit(main())
  File "/mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4/lib/python3.10/site-packages/tobias/TOBIAS.py", line 157, in main
    module = importlib.import_module(mod_name)	#load specific module
  File "/mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4/lib/python3.10/site-packages/tobias/tools/plot_aggregate.py", line 27, in <module>
    import pybedtools as pb
  File "/mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4/lib/python3.10/site-packages/pybedtools/__init__.py", line 16, in <module>
    from . import contrib
  File "/mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4/lib/python3.10/site-packages/pybedtools/contrib/__init__.py", line 3, in <module>
    from . import venn_maker
  File "/mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4/lib/python3.10/site-packages/pybedtools/contrib/venn_maker.py", line 10, in <module>
    from pybedtools import helpers
  File "/mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4/lib/python3.10/site-packages/pybedtools/helpers.py", line 15, in <module>
    import genomepy
  File "/mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4/lib/python3.10/site-packages/genomepy/__init__.py", line 10, in <module>
    from genomepy.annotation import Annotation, query_mygene
  File "/mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4/lib/python3.10/site-packages/genomepy/annotation/__init__.py", line 11, in <module>
    from genomepy.annotation.mygene import _map_genes, query_mygene
  File "/mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4/lib/python3.10/site-packages/genomepy/annotation/mygene.py", line 10, in <module>
    from genomepy.caching import cache_exp_other, disk_cache, lock
  File "/mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4/lib/python3.10/site-packages/genomepy/caching.py", line 33, in <module>
    if os.path.exists(lock_file) and time() - os.stat(lock_file).st_mtime > 60:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/home5/zoology/rm786/.cache/genomepy/0.16.1/cache.lock'
[Wed Oct 30 15:33:10 2024]
Error in rule plot_aggregate_within:
    jobid: 0
    output: sex_output/TFBS/Mecom_MA0029.2/plots/Mecom_MA0029.2_Female_aggregate.pdf
    log: sex_output/TFBS/Mecom_MA0029.2/plots/logs/Mecom_MA0029.2_Female_aggregate.log (check log file(s) for error message)
    conda-env: /mnt/beegfs/TOBIAS_snakemake/.snakemake/conda/0a1c03e4
    shell:
        TOBIAS PlotAggregate --TFBS sex_output/TFBS/Mecom_MA0029.2/beds/Mecom_MA0029.2_all.bed sex_output/TFBS/Mecom_MA0029.2/beds/Mecom_MA0029.2_Female_bound.bed sex_output/TFBS/Mecom_MA0029.2/beds/Mecom_MA0029.2_Female_unbound.bed --signals sex_output/bias_correction/Female_uncorrected.bw sex_output/bias_correction/Female_expected.bw sex_output/bias_correction/Female_corrected.bw --output sex_output/TFBS/Mecom_MA0029.2/plots/Mecom_MA0029.2_Female_aggregate.pdf --title 'Bias correction and split for Mecom_MA0029.2 in condition Female' --share_y sites --plot_boundaries > sex_output/TFBS/Mecom_MA0029.2/plots/logs/Mecom_MA0029.2_Female_aggregate.log 

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

the genomepy directory exists and I can `touch` the file:
```
touch /mnt/home5/zoology/rm786/.cache/genomepy/0.16.1/cache.lock
```

and snakemake will resume for a few hundred plots and crash again with the same error.

do you have any advice? is this a slurm issue? would it be better to put the snakemakepipeline within a single slurm job? or have I installed something incorrectly?

thanks in advance for your help.

**Comment by mohobein** [comment]
This might be a slurm-related issue if the slurm job does not have permissions to access this particular file. To check whether this is the case, you can try to check the file permissions for the slurm user with `ls -l`, or you can just run this particular `TOBIAS PlotAggregate` command on a local machine without slurm and see if that also raises the error (I am assuming that everything until this command ran without problems). 

If these steps do not help you, I have another suggestion, but I am unable to test it right now. The problem comes from genomepy's cache. You can adjust the caching behavior by [editing the configuration file](https://vanheeringen-lab.github.io/genomepy/content/config.html). Adjusting `cache_exp_other` to a much longer time might be a workaround so that the cache is not renewed during your snakemake run, but as I said, I am not entirely sure.

Let me know if you were able to resolve the issue!

**Comment by mohobein** [comment]
In general, you can find descriptions of the output files in the [wiki](url), e.g. for the BINDetect output you took as an example, they are [here](https://github.com/loosolab/TOBIAS/wiki/BINDetect). You can also just open the `_overview.xlsx` file one directory above the bed files you described, as that one has the same columns as the bed files (except that is has one more than the `_bound` and `_unbound` files to denote whether the the TFBS was bound or not. These have been left out from these two bed files as the information is already in the filename).

As you can see, first, there is the information about the TFBS, then, there is information about the peak, and the last columns afterwards contain information about the scores and bound sites (if applicable) per condition.

However, because the the snakemake pipeline uses [UROPA](https://github.com/loosolab/UROPA) to annotate the peaks before running the analysis, the peak columns contain the additional information of the annotation. To get a better understanding of these columns, take a look at the [UROPA documentation](https://uropa-manual.readthedocs.io/output.html#output-files-one-query). How the annotation is done is controlled by a configuration file, which is described [here](https://uropa-manual.readthedocs.io/config.html#queries). The snakemake pipeline builds a configuration file before it does the annotation, which can be seen [here](https://github.com/loosolab/TOBIAS_snakemake/blob/7097e8fd5eea7361c2f6e770edfe9ac32fe9e1f3/snakefiles/preprocessing.snake#L181). The config file itself can also be found in your output files (`peak_annotation/all_merged_annotated.config`). 

With this in mind, the example you provided has `NA` values for the annotated columns `feat_ovl_peak`. `peak_ovl_feat` and `gene_name`. This means that the peak and the annotated feature do no overlap at all, therefore, there is no value for the fraction of overlap and no gene that is located within the peak. As you can see in the column before these, the annotated features are located upstream or downstream of the peak, and they annotation itself (second to last column) is based on the distance (column before the `Upstream. etc.` column) to the peaks feature, which was determined by the config file. If you'd like to change this behaviour to for example only annotate features to the peaks that overlap them, you have to edit the `preprocessing.snake` snakefile accordingly.

This was a little bit of a digression, but in conclusion, the column information can basically be found in the `_overview.xlsx` file that can be found in each TFs subdirectory of the `BINDetect` output.

I hope this helped! If you have further questions, let me know!
