### ISSUE TITLE
Running example data fails with snakemake -- unkonwn error, log attached:::: NotImplementedError: function is not implemented for this dtype: [how->mean,dtype->object]

### ISSUE THREAD

**Issue by c2b2pss** [loosolab/TOBIAS_snakemake#4]
Hi,

Trying to run the example data using snakemake --- but it fails with multiple errors. Log is attached.

Sadly, I cannot figure out what the error is.  Any help is appreciated !!!

```
Activating conda environment: .snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_
Traceback (most recent call last):
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1490, in array_func
    result = self.grouper._cython_operation(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 959, in _cython_operation
    return cy_op.cython_operation(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 657, in cython_operation
    return self._cython_op_ndim_compat(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 497, in _cython_op_ndim_compat
    return self._call_cython_op(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 541, in _call_cython_op
    func = self._get_cython_function(self.kind, self.how, values.dtype, is_numeric)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 173, in _get_cython_function
    raise NotImplementedError(
NotImplementedError: function is not implemented for this dtype: [how->mean,dtype->object]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 1692, in _ensure_numeric
    x = float(x)
ValueError: could not convert string to float: 'BACH2_MA1101.2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 1696, in _ensure_numeric
    x = complex(x)
ValueError: could not convert string to complex: 'BACH2_MA1101.2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/bin/TOBIAS", line 8, in <module>
    sys.exit(main())
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/tobias/tools/plot_changes.py", line 94, in run_plotchanges
    table = bindetect.loc[chosen_TFS,].groupby("cluster").mean() #mean of each column
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1855, in mean
    result = self._cython_agg_general(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1507, in _cython_agg_general
    new_mgr = data.grouped_reduce(array_func)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 1503, in grouped_reduce
    applied = sb.apply(func)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 329, in apply
    result = func(self.values, **kwargs)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1503, in array_func
    result = self._agg_py_fallback(values, ndim=data.ndim, alt=alt)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1457, in _agg_py_fallback
    res_values = self.grouper.agg_series(ser, alt, preserve_dtype=True)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 994, in agg_series
    result = self._aggregate_series_pure_python(obj, func)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 1015, in _aggregate_series_pure_python
    res = func(group)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1857, in <lambda>
    alt=lambda x: Series(x).mean(numeric_only=numeric_only),
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/generic.py", line 11563, in mean
    return NDFrame.mean(self, axis, skipna, numeric_only, **kwargs)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/generic.py", line 11208, in mean
    return self._stat_function(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/generic.py", line 11165, in _stat_function
    return self._reduce(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/series.py", line 4671, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 96, in _f
    return f(*args, **kwargs)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 158, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 421, in new_func
    result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 727, in nanmean
    the_sum = _ensure_numeric(values.sum(axis, dtype=dtype_sum))
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 1699, in _ensure_numeric
    raise TypeError(f"Could not convert {x} to numeric") from err
TypeError: Could not convert BACH2_MA1101.2 to numeric
[Mon Apr 17 14:10:32 2023]
Error in rule lineplot_changes:
    jobid: 25
    input: test_output/TFBS/bindetect_results.txt
    output: test_output/overview/bindetect_results_subset.txt, test_output/overview/most_changed_TFs.txt, test_output/overview/TF_changes.pdf
    log: test_output/logs/TF_changes.log (check log file(s) for error details)
    conda-env: /home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_
    shell:
        filter_important_factors.py -in test_output/TFBS/bindetect_results.txt -filter 5 -o test_output/overview/bindetect_results_subset.txt > test_output/overview/most_changed_TFs.txt;TOBIAS PlotChanges --bindetect test_output/TFBS/bindetect_results.txt --TFS test_output/overview/most_changed_TFs.txt --output test_output/overview/TF_changes.pdf > test_output/logs/TF_changes.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

```

**Comment by c2b2pss** [comment]
LOG FILE:

```
Activating conda environment: .snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_
Traceback (most recent call last):
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1490, in array_func
    result = self.grouper._cython_operation(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 959, in _cython_operation
    return cy_op.cython_operation(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 657, in cython_operation
    return self._cython_op_ndim_compat(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 497, in _cython_op_ndim_compat
    return self._call_cython_op(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 541, in _call_cython_op
    func = self._get_cython_function(self.kind, self.how, values.dtype, is_numeric)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 173, in _get_cython_function
    raise NotImplementedError(
NotImplementedError: function is not implemented for this dtype: [how->mean,dtype->object]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 1692, in _ensure_numeric
    x = float(x)
ValueError: could not convert string to float: 'BACH2_MA1101.2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 1696, in _ensure_numeric
    x = complex(x)
ValueError: could not convert string to complex: 'BACH2_MA1101.2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/bin/TOBIAS", line 8, in <module>
    sys.exit(main())
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/tobias/TOBIAS.py", line 154, in main
    args.func(args)		
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/tobias/tools/plot_changes.py", line 94, in run_plotchanges
    table = bindetect.loc[chosen_TFS,].groupby("cluster").mean() #mean of each column
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1855, in mean
    result = self._cython_agg_general(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1507, in _cython_agg_general
    new_mgr = data.grouped_reduce(array_func)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 1503, in grouped_reduce
    applied = sb.apply(func)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 329, in apply
    result = func(self.values, **kwargs)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1503, in array_func
    result = self._agg_py_fallback(values, ndim=data.ndim, alt=alt)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1457, in _agg_py_fallback
    res_values = self.grouper.agg_series(ser, alt, preserve_dtype=True)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 994, in agg_series
    result = self._aggregate_series_pure_python(obj, func)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/ops.py", line 1015, in _aggregate_series_pure_python
    res = func(group)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/groupby/groupby.py", line 1857, in <lambda>
    alt=lambda x: Series(x).mean(numeric_only=numeric_only),
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/generic.py", line 11563, in mean
    return NDFrame.mean(self, axis, skipna, numeric_only, **kwargs)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/generic.py", line 11208, in mean
    return self._stat_function(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/generic.py", line 11165, in _stat_function
    return self._reduce(
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/series.py", line 4671, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 96, in _f
    return f(*args, **kwargs)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 158, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 421, in new_func
    result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 727, in nanmean
    the_sum = _ensure_numeric(values.sum(axis, dtype=dtype_sum))
  File "/home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_/lib/python3.10/site-packages/pandas/core/nanops.py", line 1699, in _ensure_numeric
    raise TypeError(f"Could not convert {x} to numeric") from err
TypeError: Could not convert BACH2_MA1101.2 to numeric
[Mon Apr 17 14:10:32 2023]
Error in rule lineplot_changes:
    jobid: 25
    input: test_output/TFBS/bindetect_results.txt
    output: test_output/overview/bindetect_results_subset.txt, test_output/overview/most_changed_TFs.txt, test_output/overview/TF_changes.pdf
    log: test_output/logs/TF_changes.log (check log file(s) for error details)
    conda-env: /home/user/TOBIAS_snakemake/.snakemake/conda/b64f8cafc44f6fd604e0d4c62f7a507d_
    shell:
        filter_important_factors.py -in test_output/TFBS/bindetect_results.txt -filter 5 -o test_output/overview/bindetect_results_subset.txt > test_output/overview/most_changed_TFs.txt;TOBIAS PlotChanges --bindetect test_output/TFBS/bindetect_results.txt --TFS test_output/overview/most_changed_TFs.txt --output test_output/overview/TF_changes.pdf > test_output/logs/TF_changes.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Comment by aksarkar** [comment]
I had the same problem. However, I found that running the job manually worked

```
conda activate .snakemake/conda/cb62d560d34b3f8ac6ac84509d05b4bb_
TOBIAS PlotChanges --bindetect test_output/TFBS/bindetect_results.txt --TFS test_output/overview/most_changed_TFs.txt --output test_output/overview/TF_changes.pdf > test_output/logs/TF_changes.log
conda deactivate
```

after which the remainder of the pipeline completed successfully.

**Comment by c2b2pss** [comment]
@aksarkar 

Thank you for your update.

So is this only happening in the test-data? Have you run the pipeline with your own data?

Thanks!
